import {
  captureInternalAuthRedirect,
  clearInternalAccessToken,
  internalAuthHeaders,
} from "../admin/internal-session-policy.js?v=1";
import {
  flattenClientProjects,
  templatePreviewUrl,
  templateProfilePayload,
  templateUpdatePayload,
} from "../admin/kreaton-admin-policy.js?v=2";

const API_BASE = String(window.LUMA_API_BASE_URL || "").replace(/\/$/, "");
const SUPABASE_URL = "https://rzdidqclbvnqqlcaueoh.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6ZGlkcWNsYnZucXFsY2F1ZW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxOTY3NzUsImV4cCI6MjA5Mzc3Mjc3NX0.R6gl2jmRRaXDzOzh_QdsAlzdzvdSyfp0muCEJGnJku0";

const state = { identity: null, view: "overview", overview: null, items: [], clients: [], templates: [], confirmAction: null, product: "all" };
const meta = {
  overview: ["PORTAFOLIO", "Inicio", "Estado general de tus productos."],
  requests: ["COLA OPERATIVA", "Solicitudes", "Borradores y trabajos que todavía requieren atención."],
  businesses: ["CUENTAS", "Negocios", "Tiendas y negocios registrados en KREATON."],
  clients: ["DIRECTORIO", "Clientes", "Todas las cuentas, incluso si todavía no crearon un proyecto."],
  orders: ["COMERCIO", "Pedidos", "Pedidos reales registrados por los negocios."],
  sites: ["PRESENCIA DIGITAL", "Páginas web", "Sitios generados, estado y dominio público."],
  products: ["CATÁLOGO", "Productos", "Inventario conectado de las tiendas KREATON."],
  payments: ["FINANZAS", "Pagos", "Eventos de pago y conciliación operativa."],
  templates: ["DISEÑO", "Plantillas", "Miniaturas, disponibilidad y reemplazos para nuevos proyectos."],
  audit: ["SEGURIDAD", "Auditoría", "Trazabilidad de consultas y acciones internas."],
  config: ["SISTEMA", "Configuración", "Estado de integraciones sin exponer credenciales."],
};
const paths = { requests:"/requests", businesses:"/businesses", orders:"/orders", sites:"/sites", products:"/products", payments:"/payments", audit:"/audit", config:"/config" };
const icons = {
  home:'<path d="M3 11 12 3l9 8v10h-6v-6H9v6H3Z"/>', inbox:'<path d="M4 4h16v13H4Z"/><path d="M4 13h4l2 3h4l2-3h4"/>',
  store:'<path d="M3 9 5 3h14l2 6M5 13v8h14v-8"/><path d="M3 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0"/>',
  orders:'<path d="M6 2h12v20H6Z"/><path d="M9 7h6M9 11h6M9 15h4"/>', pages:'<path d="M6 2h9l5 5v15H6Z"/><path d="M15 2v6h5"/>',
  box:'<path d="m4 7 8-4 8 4-8 4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/>', card:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/>',
  activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>', settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a2 2 0 0 0 .4 2.2l.1.1-2.6 2.6-.1-.1a2 2 0 0 0-2.2-.4 2 2 0 0 0-1.2 1.8V21h-3.6v-.2A2 2 0 0 0 9 19a2 2 0 0 0-2.2.4l-.1.1-2.6-2.6.1-.1A2 2 0 0 0 4.6 15 2 2 0 0 0 3 13.8H3v-3.6h.2A2 2 0 0 0 5 9a2 2 0 0 0-.4-2.2l-.1-.1 2.6-2.6.1.1A2 2 0 0 0 9 4.6 2 2 0 0 0 10.2 3H14a2 2 0 0 0 1.2 1.6 2 2 0 0 0 2.2-.4l.1-.1 2.6 2.6-.1.1A2 2 0 0 0 19.4 9a2 2 0 0 0 1.6 1.2V14a2 2 0 0 0-1.6 1Z"/>',
  logout:'<path d="m10 17 5-5-5-5M15 12H3"/><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/>', menu:'<path d="M4 6h16M4 12h16M4 18h16"/>', refresh:'<path d="M20 11a8 8 0 0 0-15-3M4 4v5h5M4 13a8 8 0 0 0 15 3M20 20v-5h-5"/>', external:'<path d="M14 3h7v7M10 14 21 3"/><path d="M18 13v7H4V6h7"/>', users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/>', layout:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/>', edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2 2 0 0 1 3 3L8 18l-4 1 1-4Z"/>'
};

function icon(name){ return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[name]||icons.pages}</svg>`; }
function hydrate(){ document.querySelectorAll("[data-icon]").forEach(n=>n.innerHTML=icon(n.dataset.icon)); }
function esc(value){ return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"); }
function money(cents){ return new Intl.NumberFormat("es-US",{style:"currency",currency:"USD"}).format(Number(cents||0)/100); }
function date(value){ if(!value)return "Sin fecha"; const n=Number(value); const d=new Date(Number.isFinite(n)&&n<1e12?n*1000:value); return Number.isNaN(d.getTime())?"Sin fecha":new Intl.DateTimeFormat("es",{day:"2-digit",month:"short",year:"numeric"}).format(d); }
function badge(value){ const v=String(value||"unknown").toLowerCase(); return `<span class="badge ${esc(v)}">${esc(value||"Sin estado")}</span>`; }
async function api(path, options={}){ const r=await fetch(`${API_BASE}/api/operations${path}`,{credentials:"include",...options,headers:internalAuthHeaders(sessionStorage,{"Content-Type":"application/json",...(options.headers||{})})}); let b={}; try{b=await r.json();}catch{} if(!r.ok){const e=new Error(b.detail||"No se pudo completar la solicitud.");e.status=r.status;throw e;} return b; }
async function adminApi(path, options={}){ const r=await fetch(`${API_BASE}${path}`,{credentials:"include",...options,headers:internalAuthHeaders(sessionStorage,{"Content-Type":"application/json",...(options.headers||{})})}); let b={}; try{b=await r.json();}catch{} if(!r.ok){const e=new Error(b.detail||"No se pudo completar la solicitud.");e.status=r.status;throw e;} return b; }
function callbackToken(){ const result=captureInternalAuthRedirect(location,sessionStorage); if(result.token||result.error)history.replaceState({},document.title,location.pathname+location.search); return result; }
function setLogin(message=""){ document.querySelector("#loginStatus").textContent=message; }
async function boot(){ hydrate(); const {token,error}=callbackToken(); if(error){showLogin(decodeURIComponent(error.replaceAll("+"," ")));return;} try{ state.identity=token?await api("/auth/session",{method:"POST",body:JSON.stringify({access_token:token})}):await api("/auth/me"); showApp(); }catch(e){ showLogin(e.message||"No se pudo completar el acceso."); } }
function showLogin(message=""){ document.querySelector("#loginScreen").classList.remove("hidden");document.querySelector("#appShell").classList.add("hidden");setLogin(message); }
function showApp(){ document.querySelector("#loginScreen").classList.add("hidden");document.querySelector("#appShell").classList.remove("hidden"); const email=state.identity.email||"Cuenta";document.querySelector("#sessionEmail").textContent=email;document.querySelector("#sessionRole").textContent=state.identity.role.replace("vm_","").replace("_"," ");document.querySelector("#avatar").textContent=email[0].toUpperCase();load("overview"); }
function loading(){ document.querySelector("#content").innerHTML='<div class="surface empty"><span class="spinner"></span><p>Cargando datos reales...</p></div>'; }
function error(message){ document.querySelector("#content").innerHTML=`<div class="surface empty"><h2>No pudimos cargar esta vista</h2><p>${esc(message)}</p><button class="primary-button" data-retry>Reintentar</button></div>`; }
function setChrome(){ const [k,t,s]=meta[state.view];document.querySelector("#viewKicker").textContent=k;document.querySelector("#viewTitle").textContent=t;document.querySelector("#viewSubtitle").textContent=s;document.querySelectorAll("#mainNav button").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view)); }
async function load(view){ state.view=view;setChrome();loading();try{ if(view==="overview")state.overview=await api("/overview");else if(view==="clients"){const body=await adminApi("/api/admin/clients?per_page=100");state.clients=body.clients||[];}else if(view==="templates"){const body=await adminApi("/api/admin/templates");state.templates=body.templates||[];}else state.items=(await api(paths[view])).items||[];render(); }catch(e){if(e.status===401){showLogin("Tu sesión terminó.");return;}error(e.message);} }
function stats(){ const o=state.overview;if(!o){document.querySelector("#stats").innerHTML="";return;} const rows=[[o.businesses,"Negocios"],[o.publishedSites,"Sitios publicados"],[o.orders,"Pedidos"],[money(o.revenueCents),"Ventas registradas"]];document.querySelector("#stats").innerHTML=rows.map(([v,l])=>`<article><strong>${esc(v)}</strong><span>${l}</span></article>`).join(""); }
function surface(title,subtitle,body,action=""){return `<section class="surface"><header><div><h2>${title}</h2><p>${subtitle}</p></div>${action}</header>${body}</section>`;}
function empty(label){return `<div class="empty"><h3>No hay ${label}</h3><p>Esta vista usa datos reales. No mostramos registros de demostración cuando la fuente está vacía.</p></div>`;}
function table(columns,rows){if(!rows.length)return empty("registros todavía");return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${c.label}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td data-label="${c.label}">${c.render?c.render(row):esc(row[c.key])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;}
function renderOverview(){const o=state.overview; const products=o.productsStatus.map(p=>`<article class="product-card"><div class="product-mark ${p.id}">${p.name[0]}</div><div><h3>${p.name}</h3><p>${p.id==="listo"?"Administración aislada, con permisos y datos propios.":"Constructor, sitios, comercio y clientes."}</p></div><span class="badge ${p.status}">${p.status==="connected"?"Conectado":"Panel separado"}</span><a href="${esc(p.url)}">Abrir ${p.name} ${icon("external")}</a></article>`).join(""); const queue=`<div class="activity-grid"><article><span>Pagos pendientes</span><strong>${o.pendingPayments}</strong></article><article><span>Productos registrados</span><strong>${o.products}</strong></article><article><span>Sitios en borrador</span><strong>${Math.max(0,o.sites-o.publishedSites)}</strong></article></div>`;document.querySelector("#content").innerHTML=surface("Productos operativos","Cada producto conserva su propio panel y sus propios datos.",`<div class="product-grid">${products}</div>`)+surface("Pulso de KREATON","Indicadores consolidados de la base conectada.",queue);}
function renderList(){let columns=[];if(state.view==="requests")columns=[{key:"businessName",label:"Negocio",render:r=>`<strong>${esc(r.businessName)}</strong><small>${esc(r.email)}</small>`},{key:"template",label:"Plantilla"},{key:"status",label:"Estado",render:r=>badge(r.status)},{key:"updatedAt",label:"Actualizado",render:r=>date(r.updatedAt)}];if(state.view==="businesses")columns=[{key:"name",label:"Negocio",render:r=>`<strong>${esc(r.name)}</strong><small>${esc(r.email)}</small>`},{key:"type",label:"Tipo"},{key:"status",label:"Estado",render:r=>badge(r.status)},{key:"publicUrl",label:"Sitio",render:r=>r.publicUrl?`<a href="${esc(r.publicUrl)}" target="_blank">Abrir</a>`:"Sin URL"}];if(state.view==="orders")columns=[{key:"number",label:"Pedido",render:r=>`<strong>${esc(r.number)}</strong><small>${esc(r.business)}</small>`},{key:"items",label:"Ítems"},{key:"totalCents",label:"Total",render:r=>money(r.totalCents)},{key:"status",label:"Estado",render:r=>badge(r.status)},{key:"createdAt",label:"Fecha",render:r=>date(r.createdAt)}];if(state.view==="sites")columns=[{key:"businessName",label:"Página",render:r=>`<strong>${esc(r.businessName)}</strong><small>${esc(r.email)}</small>`},{key:"template",label:"Plantilla"},{key:"status",label:"Estado",render:r=>badge(r.status)},{key:"publicUrl",label:"Dominio",render:r=>r.publicUrl?`<a href="${esc(r.publicUrl)}" target="_blank">Visitar</a>`:"Sin dominio"},{key:"id",label:"Acción",render:r=>state.identity?.role==="vm_super_admin"?`<button class="table-danger" data-delete-site="${esc(r.id)}" type="button">Eliminar</button>`:"Solo lectura"}];if(state.view==="products")columns=[{key:"name",label:"Producto",render:r=>`<strong>${esc(r.name)}</strong><small>${esc(r.business)}</small>`},{key:"category",label:"Categoría"},{key:"priceCents",label:"Precio",render:r=>money(r.priceCents)},{key:"inventory",label:"Inventario"},{key:"status",label:"Estado",render:r=>badge(r.status)}];if(state.view==="payments")columns=[{key:"number",label:"Pedido",render:r=>`<strong>${esc(r.number)}</strong><small>${esc(r.business)}</small>`},{key:"provider",label:"Proveedor"},{key:"amountCents",label:"Monto",render:r=>money(r.amountCents)},{key:"status",label:"Estado",render:r=>badge(r.status)},{key:"createdAt",label:"Fecha",render:r=>date(r.createdAt)}];document.querySelector("#content").innerHTML=surface(meta[state.view][1],meta[state.view][2],table(columns,state.items));}
function renderConfig(){ const rows=state.items.map(i=>`<article class="config-row"><span class="config-dot ${i.configured?"ok":"off"}"></span><div><strong>${esc(i.label)}</strong><small>${i.configured?"Configurado":"No configurado"}</small></div>${i.url?`<a href="${esc(i.url)}">Abrir</a>`:""}</article>`).join("");document.querySelector("#content").innerHTML=surface("Estado del sistema","Lectura segura: nunca se muestran claves o secretos.",`<div class="config-list">${rows}</div>`);}
function renderAudit(){const cols=[{key:"action",label:"Acción",render:r=>`<strong>${esc(r.action)}</strong><small>${esc(r.actor?.email||"")}</small>`},{key:"target",label:"Objetivo",render:r=>esc(`${r.target?.type||""}: ${r.target?.id||""}`)},{key:"outcome",label:"Resultado",render:r=>badge(r.outcome)},{key:"createdAt",label:"Fecha",render:r=>date(r.createdAt)}];document.querySelector("#content").innerHTML=surface("Auditoría corporativa","Consultas realizadas desde VM Operations.",table(cols,state.items));}
function renderClients(){const rows=state.clients.map(client=>({email:client.email,status:client.accountStatus,projects:client.projectCount||0,registered:client.createdAt,last:client.lastActivityAt}));const cols=[{key:"email",label:"Cuenta",render:r=>`<strong>${esc(r.email)}</strong>`},{key:"status",label:"Estado",render:r=>badge(r.status)},{key:"projects",label:"Proyectos"},{key:"registered",label:"Registro",render:r=>date(r.registered)},{key:"last",label:"Actividad",render:r=>date(r.last)}];document.querySelector("#content").innerHTML=surface("Directorio de clientes","Incluye cuentas de Supabase aunque todavía no tengan proyectos.",table(cols,rows));}
function renderTemplates(){const cards=state.templates.map(t=>{const preview=t.interactivePreviewUrl||`/templates-preview/live-preview.html?template=${encodeURIComponent(t.templateId)}`;const thumbnail=templatePreviewUrl(t);const media=/\.(?:avif|gif|jpe?g|png|webp)(?:\?|$)/i.test(thumbnail)?`<img loading="lazy" src="${esc(thumbnail)}" alt="Miniatura de ${esc(t.name)}">`:`<iframe loading="lazy" src="${esc(preview)}" title="Miniatura de ${esc(t.name)}" tabindex="-1"></iframe>`;return `<article class="template-card ${t.enabled?"":"disabled"}"><div class="template-visual">${media}<div class="template-visual-shade"></div><div class="template-visual-top">${badge(t.enabled?"active":"suspended")}<span class="template-maturity">${esc(t.designMaturity||"standard")}</span></div><a class="template-preview-link" href="${esc(preview)}" target="_blank" rel="noopener">${icon("external")} Ver preview</a></div><div class="template-card-body"><div class="template-card-header"><div><h3>${esc(t.name)}</h3><p>${esc(t.templateId)}</p></div><button class="icon-button template-edit-button" data-edit-template="${esc(t.templateId)}" type="button" title="Editar">${icon("edit")}</button></div><div class="template-meta"><span class="badge">${esc(t.websiteType)}</span><span class="badge">${esc(t.catalogType)}</span></div><p class="template-audience">${esc(t.audience||"Audiencia general")}</p>${t.replacementTemplateId?`<p class="template-replacement">Reemplazo: <strong>${esc(t.replacementTemplateId)}</strong></p>`:""}<footer><small>${esc(t.reason||"Configuración original")}</small><label class="switch" title="${t.enabled?"Desactivar":"Activar"}"><input data-template-toggle="${esc(t.templateId)}" type="checkbox" ${t.enabled?"checked":""}><span></span></label></footer></div></article>`}).join("");document.querySelector("#content").innerHTML=surface("Catálogo visual de plantillas","Editar, reemplazar o pausar sin afectar sitios existentes.",`<div class="template-grid">${cards}</div>`,`<span class="badge active">${state.templates.filter(t=>t.enabled).length} activas</span>`);}
function render(){stats();if(state.view==="overview")renderOverview();else if(state.view==="clients")renderClients();else if(state.view==="templates")renderTemplates();else if(state.view==="config")renderConfig();else if(state.view==="audit")renderAudit();else renderList();}

function openTemplateEditor(template){const modal=document.querySelector("#templateEditorModal");const form=document.querySelector("#templateEditorForm");form.elements.templateId.value=template.templateId;form.elements.name.value=template.name||"";form.elements.audience.value=template.audience||"";form.elements.previewUrl.value=template.previewUrl||"";form.elements.reason.value="";form.elements.replacementTemplateId.innerHTML=`<option value="">Sin reemplazo</option>${state.templates.filter(item=>item.templateId!==template.templateId&&item.enabled).map(item=>`<option value="${esc(item.templateId)}">${esc(item.name)}</option>`).join("")}`;form.elements.replacementTemplateId.value=template.replacementTemplateId||"";document.querySelector("#templateEditorTitle").textContent=template.name;document.querySelector("#templateEditorStatus").textContent="";modal.classList.remove("hidden");}
function closeTemplateEditor(){document.querySelector("#templateEditorModal").classList.add("hidden");}
function showConfirm({title,description,label,button,placeholder,action,onCancel}){state.confirmAction=action;const modal=document.querySelector("#confirmModal");modal._onCancel=onCancel;document.querySelector("#confirmTitle").textContent=title;document.querySelector("#confirmDescription").textContent=description;document.querySelector("#confirmInputLabel").textContent=label;document.querySelector("#acceptConfirmButton").textContent=button;document.querySelector("#confirmInput").value="";document.querySelector("#confirmInput").placeholder=placeholder||"";document.querySelector("#confirmStatus").textContent="";modal.classList.remove("hidden");}
function closeConfirm(cancel=false){const modal=document.querySelector("#confirmModal");if(cancel&&modal._onCancel)modal._onCancel();modal._onCancel=null;state.confirmAction=null;modal.classList.add("hidden");}
function requestTemplateToggle(template,enabled,checkbox){showConfirm({title:enabled?"Activar plantilla":"Pausar plantilla",description:enabled?`${template.name} volverá a ofrecerse en proyectos nuevos.`:`${template.name} dejará de ofrecerse en proyectos nuevos. Los sitios existentes no cambian.`,label:"Motivo del cambio",button:enabled?"Activar plantilla":"Pausar plantilla",placeholder:"Ej. revisión visual o control de calidad",onCancel:()=>{checkbox.checked=template.enabled;},action:async reason=>{const body=await adminApi(`/api/admin/templates/${encodeURIComponent(template.templateId)}`,{method:"PATCH",body:JSON.stringify(templateUpdatePayload(enabled,reason))});state.templates=state.templates.map(item=>item.templateId===body.template.templateId?body.template:item);closeConfirm();renderTemplates();}});}
function requestSiteDelete(site){showConfirm({title:"Eliminar proyecto",description:`Esta acción elimina “${site.businessName}”, sus sesiones y assets asociados. No se puede deshacer.`,label:`Escribe “${site.businessName}” para confirmar`,button:"Eliminar definitivamente",placeholder:site.businessName,action:async name=>{await adminApi(`/api/admin/clients/${encodeURIComponent(site.id)}`,{method:"DELETE",body:JSON.stringify({businessName:name})});state.items=state.items.filter(item=>item.id!==site.id);closeConfirm();renderList();}});}
document.addEventListener("click",e=>{const nav=e.target.closest("#mainNav button");if(nav){load(nav.dataset.view);document.body.classList.remove("nav-open");}if(e.target.closest("[data-retry]"))load(state.view);if(e.target.closest("#refreshButton"))load(state.view);if(e.target.closest("#mobileMenu"))document.body.classList.toggle("nav-open");const edit=e.target.closest("[data-edit-template]");if(edit){const template=state.templates.find(item=>item.templateId===edit.dataset.editTemplate);if(template)openTemplateEditor(template);}const remove=e.target.closest("[data-delete-site]");if(remove){const site=state.items.find(item=>item.id===remove.dataset.deleteSite);if(site)requestSiteDelete(site);}});
document.querySelector("#content").addEventListener("change",e=>{const toggle=e.target.closest("[data-template-toggle]");if(!toggle)return;const template=state.templates.find(item=>item.templateId===toggle.dataset.templateToggle);if(template)requestTemplateToggle(template,toggle.checked,toggle);});
document.querySelector("#googleLoginButton").addEventListener("click",()=>{const redirect=encodeURIComponent(location.href.split("#")[0]);location.assign(`${SUPABASE_URL}/auth/v1/authorize?provider=google&redirect_to=${redirect}`);});
document.querySelector("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const email=document.querySelector("#emailInput").value.trim();setLogin("Enviando enlace...");const r=await fetch(`${SUPABASE_URL}/auth/v1/otp`,{method:"POST",headers:{apikey:SUPABASE_ANON_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,options:{emailRedirectTo:location.href.split("#")[0],shouldCreateUser:false}})});setLogin(r.ok?"Revisa tu correo para entrar.":"No pudimos enviar el enlace.");});
document.querySelector("#logoutButton").addEventListener("click",async()=>{await api("/auth/logout",{method:"POST"}).catch(()=>{});clearInternalAccessToken(sessionStorage);showLogin("Sesión cerrada.");});
document.querySelector("#productSwitch").addEventListener("change",e=>{if(e.target.value==="kreaton")location.href="/admin/";if(e.target.value==="listo")location.href="https://listo.vmbusinesssystems.com/admin/";e.target.value="all";});
document.querySelector("#cancelConfirmButton").addEventListener("click",()=>closeConfirm(true));
document.querySelector("#acceptConfirmButton").addEventListener("click",async()=>{if(!state.confirmAction)return;const button=document.querySelector("#acceptConfirmButton");const status=document.querySelector("#confirmStatus");button.disabled=true;status.textContent="";try{await state.confirmAction(document.querySelector("#confirmInput").value);}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});
document.querySelector("#closeTemplateEditorButton").addEventListener("click",closeTemplateEditor);
document.querySelector("#cancelTemplateEditorButton").addEventListener("click",closeTemplateEditor);
document.querySelector("#templateEditorForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget;const status=document.querySelector("#templateEditorStatus");const button=form.querySelector('[type="submit"]');button.disabled=true;status.textContent="";try{const data=Object.fromEntries(new FormData(form));const payload=templateProfilePayload(data);const body=await adminApi(`/api/admin/templates/${encodeURIComponent(data.templateId)}/profile`,{method:"PATCH",body:JSON.stringify(payload)});state.templates=state.templates.map(item=>item.templateId===body.template.templateId?body.template:item);closeTemplateEditor();renderTemplates();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
boot();
